---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pacman
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./deploy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: pacman
  targetNamespace: default
  timeout: 3m0s
  wait: true
  ignore: |
    deploy/prehook/*
    deploy/posthook/*
