# Source details: https://fluxcd.io/flux/components/source/gitrepositories/

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pacman
  namespace: flux-system
spec:
  interval: 60m0s
  ref:
    branch: main
  url: https://github.com/jnpacker/deploy
  timeout: 3m0s
  secretRef:
    name: flux-git-deploy
  ignore: install.yaml